import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import "./globalicons.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });
// const roboto = Roboto({
//   subsets: ["latin"]
// })

export const metadata = {
  title: "Linkedin X Twitch",
  description: "Generated by Adesh Singh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-stone-950 text-white`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
